language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- make html
env:
  global:
  - secure: M438xVPDRdkg7l8QvkPM1JP2zAUdsPF6BF4laUNSP6T23AfNYtOJC8Tiz+nAZIVTWxRP60QynFPTLqgIaSd6dE49fk+RHOBWZTDw5U/G60rQSgjiNPvC0f9U2+pSs/UuNGLPFVlYabVwoTQSnndyue8Sn84K8lXb4I/FvY9914NChVU7+fNXca96qPsham2NLrXINajzRASLoymBow1py0y1USuIXL5ezYiC2LL0TYzrqi7rXSZtU8GKCDI5B9975YsMW7Ms/ZdXnb1NPZGVHS8jj90WH7IG6R3ZlScyTsYNWptgATr2DjoHXbxmBAgHPCmtrf25PhCNpRPs0FD4UYMNFhcJPRpHXjA7Y6MqkR9SLnnWp+TB7vdcTW6q9OblVrW0TIMtI0z9XiJv18TI5GumnMxJYKlZEPGdJ3TqMLL5jGZ0oY3U6nmfMz8YqNdM+fLZhqHqhypQhaeIkiG/DEdOGnBW4yGYBpcKqaA2uyZ5F+v5VJQ7ttAC4lhnNWZpBqwElTxCMF0qoWGQvqLf6LqSd0dkoM6kLlE4RUywAcJU9rieRjmjzqlT9ViNIqpcIXvWf06P6u2wCpR4B0euo+vhhjhHu4fIEswA4NeTh1pCHVmdC3hbaNzgppal/zbqD/zcwJPH65Jk3jXMEmEqZsCHujbVf9gyllAy5QhE7UQ=
  - secure: C0tfoZbjJPEAmUEt98OeIBKwDtyVyRcjvAySHZHV0STaQwheusyrKfhcJyc+BonJjOdnMkrb5h6NkzOXU4NF0ceJgYVL+476vC6W1QPK/rhhLndrLR/OI2LwHzJA63gBG8OJWIIDvSXL2uBe1VuyUZUdweXIyj12rgLoJPRip0wxFo2fvg1+mrcZ5HkdZpyjEQTQOO+hoiIvWxXNXcV1Qug2kUhyBZZ5erM2AfHCUAjbIJE0w4OvSbw7cAOYCAcsN18hhTZnh7JjXxaHE4dPUhglbBJZlUOJCkG89KYmaphyJmVFR2ArBosj6bSsJalrX3NV9Af50d0+PO2wHhKrjVpBF38K5lZL6jHYjzt1IRXYocZmtvLNyYbGflH9H43z2dQ62RooMXHyyT4otijmnnz3gLeQkXd3d4g6iOydnBAgTKxgCsZ4hiBe/eNv9i+N6adsIITGBeoEJvCl1ac+L3C3yUFJcm7QDTywxXzPv9FxLgbdC3VVfjozs3P0IS+dO6DkUlXwZQ5S0aP42L0ljEAf7jNJ271cNlofURymFn9qAaT/acpTEIfepre6/JUEsXNhcZWEQaKQXkLtjQGqewhU1nNz15jKEe4VC18qx4L24ObdSJFwJRG1ARxZm0UgN26k1B5cngxS7N7gWmF0jL7ROaKN1NQzzL2ebK8ZIWs=
  - secure: JS4QTUc9gpnCYtg9Qnf3hROihJTZCGOY96/w0JJRgkn5KZL9Zn8sJOQcn41EDuQviu1DbZGenGthGsw8/IwiAnGGp35VBeA9VlICIprYvbGV8MYzhr9FB962z8dyw8lmisCvahfeNC1aMlZovHewbrunJgPOHNTUmV15QoKxgvbgeRyUKvr+bjJRweeJJLbTtc7hbXAeW9jkgU1btTgAd1Cn4FdcmAlxG0AlpNWKQ2XvfHpkf8pkaY0Ps7lPKRchE0wmX8vzV5pt0Q0pFUrt0nirBtpj7WBL0F3jcoXeZOcaSuxsncbUUWTXIdIRnMf6kmbaAeRdm8fseRBK21TjUHj72zVQL9j1GxVsIZ4wVL1K+h9/tGL9c4f8JQGnUQwD1XebZtoU335qBVGuF+E99UdTnFgEa2krfT1TcITYbx6FW0exykNuJilVzqE0y8D2OZu4CsDODFqT8ZQecvKMhzZtcSx3lGxurl/eqMyPdaU3MLkwerIe8E68PfwiotPXH4wa8sBty6NqYqUnswpCjLOscIY3n2q5I6gZHwTxlTqDFBPRHUd4GAIEPO0wGsm3jpxJvfx87xjogVCMYiZkmnLyXpzfoHhMNCxngNQnM5Ia+vrJJq/HRMArsH8vNGNDDbeh4CvPVusr5nWtFV8OyB2tHUa6JTveogbptu2faWI=
before_deploy:
- openssl aes-256-cbc -K $encrypted_a03e767856e9_key -iv $encrypted_a03e767856e9_iv
  -in id_rsa_oci_deploy.enc -out id_rsa_oci_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa_oci_deploy
- ssh-add id_rsa_oci_deploy
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r -a -v -e ssh --delete $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
    on:
        branch: master
    
